version: 2.1
  jobs:
    build:
    install_authenticate:
      docker:
        - image: cimg/node:14.5
      steps:
        - checkout
        - run:
            name: Install Dependencies
            command: . build/install.sh
        - run:
            name: Create Scratch Org
            command: . build/create-scratch-org.sh
       - run:
            name: Validate Components & Run Tests
            command: . build/test.sh   
       - store_test_results:
            path: test-results
            command: . build/create-scratch-org.sh  
    deploy-prod:
      docker:
        - image: cimg/node:14.5
      steps:
        - checkout
        - run:
            name: Install Dependencies
            command: . build/install.sh
        - run:
            name: Login to Production 
            command: . build/setup-prod.sh
       - run:
            name: Deploy to Production
            command: . build/deploy-prod.sh    
  workflows:
    version: 2.1
    basic-test:
      jobs:
        -build:
          filters:
            branches:
              ignore:
                -master
        -deploy-prod:
          filters:
            branches:
              only:
                -master
